[tool.black]
line-length = 100
extend-exclude = '''
(
  alpha-automl-venv/*
)
'''

[tool.isort]
profile = "black"
force_single_line = true
force_sort_within_sections = true
group_by_package = true
lexicographical = true
line_length = 100
skip_gitignore = true
skip_glob = ["*/alpha-automl-venv/**"]
